# A conda environment with all useful packages for pyvisgen developers
name: pyvisgen-dev
channels:
    - pytorch
    - defaults
    - conda-forge
    - nvidia
dependencies:
  - python
  - astropy<=6.1.0
  - pytorch-gpu
  - pytorch-cuda=12.1
  - torchvision
  - numpy
  - matplotlib
  - pip
  - towncrier
  - jupyter
  - pip:
    - toma
